// components/MySidebar.tsx
"use client";

import { useState, useEffect } from "react";
import { cn } from "@/lib/utils";
import { Sparkle, Flag, Home, FolderGit } from "lucide-react";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { usePathname } from "next/navigation";
import Image from "next/image";

const MySidebar = () => {
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    const savedState = localStorage.getItem("sidebar-open") === "true";
    setIsOpen(savedState);
  }, []);

  useEffect(() => {
    localStorage.setItem("sidebar-open", String(isOpen));
  }, [isOpen]);

  return (
    <aside
      className={cn(
        "fixed left-[2vh] top-1/2 -translate-y-1/2 z-50 h-[96vh] rounded-2xl p-1 transition-all duration-300",
        "bg-white/5 backdrop-blur-xl border border-white/10 shadow-lg",
        isOpen ? "w-[250px]" : "w-[65px]"
      )}
    >
      <div className="flex flex-col h-full">
        <div className="pr-[9px] my-4 flex justify-end">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setIsOpen(!isOpen)}
            className={cn(
              "text-white cursor-pointer transition-all duration-300 hover:bg-transparent",
              isOpen && "bg-cover bg-center bg-no-repeat rounded-md w-32"
            )}
            style={{
              ...(isOpen && {
                backgroundImage: `url(./logo.png)`,
              }),
            }}
          >
            {!isOpen && (
              <Image
                src="./simple_logo.png"
                alt="Logo"
                className="w-6 h-6 object-contain"
                width={24}
                height={24}
                draggable={false}
              />
            )}
          </Button>
        </div>

        <nav className="flex flex-col gap-2 text-white font-medium">
          <SidebarItem
            icon={<Home size={20} />}
            label="Home"
            href="/"
            isOpen={isOpen}
          />
          <SidebarItem
            icon={<Sparkle size={20} />}
            label="Skills"
            href="/skills"
            isOpen={isOpen}
          />
          <SidebarItem
            icon={<FolderGit size={20} />}
            label="Projects"
            href="/projects"
            isOpen={isOpen}
          />
          <SidebarItem
            icon={<Flag size={20} />}
            label="Highlights"
            href="/highlights"
            isOpen={isOpen}
          />
        </nav>
      </div>
    </aside>
  );
};

interface SidebarItemProps {
  icon: React.ReactNode;
  label: string;
  href: string;
  isOpen: boolean;
}

const SidebarItem = ({ icon, label, href, isOpen }: SidebarItemProps) => {
  const pathname = usePathname();
  const isActive = pathname === href;

  return (
    <Link
      href={href}
      className={cn(
        "flex items-center rounded-lg text-base transition-colors hover:bg-white/4",
        "h-14",
        isActive && "bg-white/5"
      )}
    >
      <div className="w-[54px] flex justify-center items-center">{icon}</div>

      <span
        className={cn(
          "overflow-hidden whitespace-nowrap transition-all duration-300",
          isOpen ? "max-w-full opacity-100" : "ml-0 max-w-0 opacity-0"
        )}
      >
        {label}
      </span>
    </Link>
  );
};

export default MySidebar;

// src/shared/components/navigation/MySidebar.vue
<template>
  <aside
    :class="[
      'fixed left-[2vh] top-1/2 -translate-y-1/2 z-50 h-[96vh] rounded-2xl p-1 transition-all duration-300',
      'bg-white/5 backdrop-blur-xl border border-white/10 shadow-lg',
      isOpen ? 'w-[250px]' : 'w-[65px]',
    ]"
  >
    <div class="flex flex-col h-full">
      <div class="pr-[9px] my-4 flex justify-end">
        <Button
          size="icon"
          variant="ghost"
          :class="[
            'text-white cursor-pointer transition-all duration-300 hover:bg-transparent border-none bg-transparent',
            isOpen ? 'bg-cover bg-center bg-no-repeat rounded-md w-32 h-8' : 'w-8 h-8',
          ]"
          :style="isOpen ? { backgroundImage: 'url(/logo.png)' } : undefined"
          @click="isOpen = !isOpen"
        >
          <img
            v-if="!isOpen"
            src="/simple_logo.png"
            alt="Logo"
            class="w-6 h-6 object-contain"
            draggable="false"
          />
        </Button>
      </div>

      <nav class="flex flex-col gap-2 text-white font-medium">
        <RouterLink
          v-for="item in items"
          :key="item.href"
          :to="item.href"
          :class="[
            'flex items-center rounded-lg text-base transition-colors hover:bg-white/4 h-14',
            route.path === item.href ? 'bg-white/5' : '',
          ]"
        >
          <div class="w-[54px] flex justify-center items-center">
            <component :is="item.icon" :size="20" />
          </div>
          <span
            :class="[
              'overflow-hidden whitespace-nowrap transition-all duration-300',
              isOpen ? 'max-w-full opacity-100' : 'ml-0 max-w-0 opacity-0',
            ]"
          >
            {{ item.label }}
          </span>
        </RouterLink>
      </nav>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { RouterLink, useRoute } from "vue-router";
import { Flag, FolderGit2, House, Sparkles } from "lucide-vue-next";
import { Button } from "@/shared/components/ui/button";

const route = useRoute();
const isOpen = ref(false);

const items = [
  { label: "Home", href: "/", icon: House },
  { label: "Skills", href: "/skills", icon: Sparkles },
  { label: "Projects", href: "/projects", icon: FolderGit2 },
  { label: "Highlights", href: "/highlights", icon: Flag },
];

onMounted(() => {
  const savedState = localStorage.getItem("sidebar-open") === "true";
  isOpen.value = savedState;
});

watch(isOpen, (value) => {
  localStorage.setItem("sidebar-open", String(value));
});
</script>
